### ISSUE TITLE
seafile server version 5.1.0 using latest?

### ISSUE THREAD

**Issue by fflo** [VGoshev/seafile-docker#3]
Hi Vladimir,

running the latest sunx/seafile image I do get the following server version clicking on about:
**Server Version: 5.1.0**
© 2016 Seafile

Shouldn't it be 6.0.7?

The hidden file .seafile_version shows 6.0.7.

**Comment by fflo** [comment]
Userlist also shows the header message: A new server version 6.0.6 is available.

**Comment by VGoshev** [comment]
Ouch, it really is. Actually looks like it's seahub issue and not my docker image issue (i.e. Seafile just shows wrong version), but I'll check it.

**Comment by VGoshev** [comment]
Yes, evelopers of seafile web interface (seahub) just don't update version string:
https://github.com/haiwen/seahub/blob/v6.0.7-server/seahub/settings.py#L473
I'll add patch to fix it. Thanks for report.

**Comment by fflo** [comment]
ahhh ok :)
Maybe it's best to push it upstream as a patch request.

It's off-topic but do you know how to setup a small footer(.html) using this docker image?

**Comment by VGoshev** [comment]
@fflo Sorry for long delay.
Fixed original issue, and as for using your personal footer.html with this docker image. More of it, according to seahub customization guide (https://manual.seafile.com/config/seahub_customization.html) It doesn't have footer anymore.

But you can follow customization manual to customize seahub using this docker image, it should work (but I didn't checked it by myself :) )
