### ISSUE TITLE
bug 6.0.10 not starting

### ISSUE THREAD

**Issue by fflo** [VGoshev/seafile-docker#6]
Hi,

latest tag 6.0.10 is no longer starting, because /usr/local/bin/seafile-admin is missing.
Can you please fix this issue?

Thx.

**Comment by VGoshev** [comment]
Thanks for report, I'll try to fix it asap

**Comment by fflo** [comment]
thx 👍

**Comment by VGoshev** [comment]
I've taken a bit more time, than I've expected, but now it fixed :)

**Comment by fflo** [comment]
How can I use the fixed image?
I've tried out to upgrade to :latest a few days ago with no success.

**Comment by VGoshev** [comment]
I've fixed bug today only, so image from few days ago won't work
